---
name: Supervisor
version: 0.02
author:
  - 'Kevin L. Esteb <kesteb@wsipc.org>'
abstract: Base environment for the Supervisor
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Badger: 0.06
  DateTime: 0.4501
  File::Pid: 0
  POE: 1.007
  Set::Light: 0.04
  Test::More: 0
configure_requires:
  Module::Build: 0.35
provides:
  Supervisor::Base:
    file: lib/Supervisor/Base.pm
    version: 0.02
  Supervisor::Class:
    file: lib/Supervisor/Class.pm
  Supervisor::Constants:
    file: lib/Supervisor/Constants.pm
  Supervisor::Controller:
    file: lib/Supervisor/Controller.pm
    version: 0.01
  Supervisor::Log:
    file: lib/Supervisor/Log.pm
  Supervisor::Process:
    file: lib/Supervisor/Process.pm
    version: 0.01
  Supervisor::ProcessFactory:
    file: lib/Supervisor/ProcessFactory.pm
    version: 0.01
  Supervisor::RPC::Client:
    file: lib/Supervisor/RPC/Client.pm
    version: 0.01
  Supervisor::RPC::Server:
    file: lib/Supervisor/RPC/Server.pm
    version: 0.01
  Supervisor::Session:
    file: lib/Supervisor/Session.pm
    version: 0.01
  Supervisor::Utils:
    file: lib/Supervisor/Utils.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
